/* ═══════════════════════════════════════════
   Instrument Curriculum Templates
   ═══════════════════════════════════════════ */
const TEMPLATES = {
    ocarina: {
        name: '오카리나', emoji: '🎵', color: '#ff7b6b', color2: '#ff9e5e', max: 40,
        weeks: [
            { week: 1, title: '오카리나와 친해지기', desc: '악기 소개, 구조 알기, 바른 자세와 악기 쥐는 법', song: '(탐색 및 소리 내보기)' },
            { week: 2, title: '예쁜 소리 만들기', desc: '텅잉(Tu) 기초, 호흡법, 솔·라·시 운지 익히기', song: '비행기 (앞부분)' },
            { week: 3, title: '기초 음계 다지기 1', desc: '도·레·미·파 운지 익히기, 롱톤 연습', song: '비행기 (완곡)' },
            { week: 4, title: '기초 음계 다지기 2', desc: '높은 도·레 운지법, 낮은음과 높은음 오가기', song: '학교 종' },
            { week: 5, title: '리듬과 박자 놀이', desc: '4분음표, 2분음표 익히기, 박자에 맞춰 텅잉', song: '나비야' },
            { week: 6, title: '왈츠 리듬 배우기', desc: '3/4박자 리듬감 익히기, 부드러운 호흡 연습', song: '뻐꾸기' },
            { week: 7, title: '쉼표의 미학', desc: '쉼표 지키기, 호흡 조절하며 끊어 불기', song: '산토끼' },
            { week: 8, title: '낮은 음 정복하기', desc: '낮은 시·라 운지법, 호흡을 안정적으로 내리기', song: '작은 별' },
            { week: 9, title: '중간 점검 및 복습', desc: '운지법 총정리, 좋아하는 곡 연주', song: '(배운 곡 중 선택)' },
            { week: 10, title: '스타카토 익히기', desc: '짧고 경쾌하게 텅잉하기(Tut), 리듬감 살리기', song: '거미' },
            { week: 11, title: '이음줄(Slur) 연주', desc: '부드럽게 이어서 불기, 텅잉 없이 음 연결', song: '아빠 힘내세요' },
            { week: 12, title: '점음표 리듬 배우기', desc: '점4분음표 리듬감(딴~따) 익히기', song: '곰 세 마리' },
            { week: 13, title: '높은 음 도전하기', desc: '높은 미·파 운지법, 고음역대 호흡', song: '얼굴 찌푸리지 말아요' },
            { week: 14, title: '셈여림 표현하기', desc: '크레센도, 데크레센도 맛보기', song: '고향의 봄' },
            { week: 15, title: '2중주 맛보기', desc: '두 그룹으로 나누어 화음의 재미 느끼기', song: '(쉬운 동요 2성부)' },
            { week: 16, title: '나의 18번 만들기 1', desc: '발표회 곡 선정 및 악보 리딩', song: '(자유곡 선정)' },
            { week: 17, title: '나의 18번 만들기 2', desc: '구간 반복 연습, 안 되는 부분 집중 레슨', song: '(자유곡)' },
            { week: 18, title: '앙상블 연습', desc: '친구들과 호흡 맞추기, 박자 맞추기', song: '(합주곡)' },
            { week: 19, title: '리허설', desc: '발표회 예행 연습, 무대 매너 배우기', song: '전체 곡' },
            { week: 20, title: '기초 과정 음악회', desc: '기초 과정 발표 및 수료', song: '-' },
            { week: 21, title: '반음 운지법 1', desc: '파#(F#) 운지, 반음의 개념 이해', song: '그리운 금강산' },
            { week: 22, title: '반음 운지법 2', desc: '솔#(G#), 도#(C#) 운지 익히기', song: '스와니강' },
            { week: 23, title: '비브라토 기초', desc: '호흡 떨림으로 음색 풍부하게 만들기', song: '아리랑' },
            { week: 24, title: '트릴과 꾸밈음', desc: '빠른 운지 전환 기법 연습', song: '도라에몽' },
            { week: 25, title: '더블 텅잉', desc: 'Tu-Ku 발음으로 빠른 리듬 연주', song: '터키 행진곡(일부)' },
            { week: 26, title: '16분음표 리듬', desc: '빠른 리듬 패턴 연습', song: '캉캉' },
            { week: 27, title: '다장조 스케일 완성', desc: '내림 음까지 포함한 스케일 연습', song: '(스케일)' },
            { week: 28, title: '가단조 곡 연주', desc: '가단조(Am) 감성 곡 연주', song: '슬픈 인형' },
            { week: 29, title: '심화 중간 발표회', desc: '심화 기법 발표 및 점검', song: '(선택곡)' },
            { week: 30, title: '앙상블 심화', desc: '3성부 화음 맛보기', song: '(3성부 곡)' },
            { week: 31, title: '듀엣 연주', desc: '파트너와 호흡 맞추기', song: '(듀엣곡)' },
            { week: 32, title: '클래식 명곡 도전 1', desc: '쉬운 클래식 편곡 연주', song: '엘리제를 위하여(일부)' },
            { week: 33, title: '클래식 명곡 도전 2', desc: '박자와 셈여림 완성', song: '캐논 변주곡' },
            { week: 34, title: '인기곡 편곡 1', desc: 'K-POP/동요 편곡 연주', song: '(인기곡)' },
            { week: 35, title: '인기곡 편곡 2', desc: '반주에 맞춰 연주', song: '(인기곡)' },
            { week: 36, title: '즉흥 연주 기초', desc: '간단한 멜로디 만들기', song: '(자유 멜로디)' },
            { week: 37, title: '나만의 곡 만들기', desc: '8마디 작곡 도전', song: '(창작곡)' },
            { week: 38, title: '졸업곡 준비 1', desc: '졸업 발표곡 선정 및 연습', song: '(자유곡)' },
            { week: 39, title: '졸업곡 준비 2', desc: '세부 완성 및 리허설', song: '(자유곡)' },
            { week: 40, title: '졸업 음악회', desc: '심화 과정 수료 발표회', song: '전체 레퍼토리' },
        ]
    },
    ukulele: {
        name: '우쿨렐레', emoji: '🎸', color: '#4ecdc4', color2: '#45b7d1', max: 40,
        weeks: [
            { week: 1, title: '우쿨렐레와 안녕?', desc: '악기 명칭, 안는 자세, 줄 번호 알기, 개방현 튕기기', song: '(줄 튕겨보기 놀이)' },
            { week: 2, title: '첫 번째 코드 C', desc: '왼손 손가락 번호, C코드 잡기, 엄지 스트로크', song: '곰 세 마리' },
            { week: 3, title: '친구 코드 F', desc: 'F코드 운지법, C-F 코드 연결 연습', song: '거미' },
            { week: 4, title: '아기 코드 C7', desc: 'C7코드 운지법, 코드 체인지(C-C7-F)', song: '솜사탕' },
            { week: 5, title: '4비트 리듬 치기', desc: '검지 스트로크(다운-업), 4비트 고고 리듬', song: '나비야' },
            { week: 6, title: '국민 코드 G7', desc: 'G7코드 운지법, C-F-G7 진행', song: '올챙이와 개구리' },
            { week: 7, title: '8비트 리듬 맛보기', desc: '다운-업 스트로크 연결, 8비트 고고 리듬 기초', song: '동물농장' },
            { week: 8, title: '왈츠 리듬 배우기', desc: '3/4박자 쿵-짝-짝 리듬 치기', song: '생일 축하합니다' },
            { week: 9, title: '칼립소 리듬 1', desc: '다운-다운업-업-다운업 입으로 익히기', song: '(리듬 집중 연습)' },
            { week: 10, title: '칼립소 리듬 2', desc: '칼립소 리듬을 곡에 적용하기', song: '조개 껍질 묶어' },
            { week: 11, title: 'Am 코드와 마이너', desc: 'Am, Dm 코드 익히기, 슬픈 느낌의 곡', song: '칠갑산(멜로디만)' },
            { week: 12, title: '셔플 리듬', desc: '깡충깡충 뛰는 리듬(스윙) 느낌', song: '숲 속의 음악가' },
            { week: 13, title: 'TAB 악보 보기', desc: '멜로디 연주 기초, 도레미파솔라시도 찾기', song: '학교 종(멜로디)' },
            { week: 14, title: '멜로디와 반주', desc: '선생님 반주에 맞춰 멜로디 쳐보기', song: '작은 별' },
            { week: 15, title: '컷팅 주법 1', desc: '오른손 컷팅(착!), 리듬에 악센트 넣기', song: '멋쟁이 토마토' },
            { week: 16, title: '나의 애창곡 연습 1', desc: '발표회 곡 선정, 코드 진행 반복 숙달', song: '(자유곡)' },
            { week: 17, title: '나의 애창곡 연습 2', desc: '노래 부르며 연주하기', song: '(자유곡)' },
            { week: 18, title: '합주 연습', desc: '그룹별 연습(멜로디/반주 파트)', song: '(합주곡)' },
            { week: 19, title: '리허설', desc: '모의 발표회, 서로 들어주고 박수치기', song: '전체 곡' },
            { week: 20, title: '기초 과정 음악회', desc: '기초 과정 발표 및 수료식', song: '-' },
            { week: 21, title: '바레 코드 입문', desc: 'Bb, Bm 코드 잡기', song: '사랑의 인사' },
            { week: 22, title: '바레 코드 연습', desc: '바레 코드 전환 훈련', song: '봄봄봄' },
            { week: 23, title: '핑거피킹 기초', desc: '엄지+검지 아르페지오 패턴', song: '로망스' },
            { week: 24, title: '핑거피킹 패턴', desc: '다양한 아르페지오 패턴 연습', song: '별빛 야경' },
            { week: 25, title: '하이 코드', desc: '5프렛 이상 코드 잡기', song: '(코드 연습)' },
            { week: 26, title: '블루스 리듬', desc: '12마디 블루스 진행', song: '블루스 잼' },
            { week: 27, title: '팝송 반주 1', desc: '대중가요 코드 진행 분석', song: '(인기곡)' },
            { week: 28, title: '팝송 반주 2', desc: '노래하며 연주하기', song: '(인기곡)' },
            { week: 29, title: '심화 중간 발표회', desc: '심화 과정 중간 점검', song: '(선택곡)' },
            { week: 30, title: '하모닉스', desc: '자연 하모닉스 소리 내기', song: '(하모닉스 연습)' },
            { week: 31, title: '슬라이드/해머온', desc: '왼손 기법 연습', song: '(기법 연습곡)' },
            { week: 32, title: '풀-오프', desc: '왼손 기법 심화', song: '(기법 연습곡)' },
            { week: 33, title: '솔로 연주 기초', desc: '코드+멜로디 동시 연주', song: '(솔로 편곡)' },
            { week: 34, title: '솔로 연주 심화', desc: '반주 위에 멜로디 얹기', song: '(솔로 편곡)' },
            { week: 35, title: '앙상블 심화', desc: '3파트 합주', song: '(합주곡)' },
            { week: 36, title: '보사노바 리듬', desc: '브라질 리듬 패턴', song: '이파네마의 소녀' },
            { week: 37, title: '레게 리듬', desc: '오프비트 스트럼 연습', song: '(레게곡)' },
            { week: 38, title: '졸업곡 준비 1', desc: '졸업 발표곡 선정', song: '(자유곡)' },
            { week: 39, title: '졸업곡 준비 2', desc: '완성도 높이기', song: '(자유곡)' },
            { week: 40, title: '졸업 음악회', desc: '심화 과정 수료 발표회', song: '전체 레퍼토리' },
        ]
    },
    kalimba: {
        name: '칼림바', emoji: '🪇', color: '#f59e0b', color2: '#fbbf24', max: 12,
        weeks: [
            { week: 1, title: '칼림바와 만나기', desc: '악기 구조, 건반 배열 알기, 바른 자세', song: '(소리 탐색)' },
            { week: 2, title: '첫 소리 내기', desc: '엄지로 건반 튕기기, 음계(도레미) 찾기', song: '(음계 연습)' },
            { week: 3, title: '기본 음계 익히기', desc: '도레미파솔라시도, 왼손/오른손 교대', song: '비행기' },
            { week: 4, title: '첫 곡 도전', desc: '간단한 멜로디 연주', song: '학교 종' },
            { week: 5, title: '리듬과 박자', desc: '4분음표, 2분음표 리듬에 맞춰 연주', song: '나비야' },
            { week: 6, title: '화음 맛보기', desc: '두 건반 동시 치기, 간단한 화음', song: '작은 별' },
            { week: 7, title: '글리산도와 꾸밈', desc: '건반 쓸어치기, 트레몰로 기법', song: '곰 세 마리' },
            { week: 8, title: '동요 연주', desc: '동요 완곡 연주', song: '아빠 힘내세요' },
            { week: 9, title: '아르페지오 반주', desc: '아르페지오 패턴으로 반주 만들기', song: '캐논(간단ver)' },
            { week: 10, title: '힐링 곡 연주', desc: '잔잔한 곡 연주, 셈여림 표현', song: 'River Flows in You(일부)' },
            { week: 11, title: '발표곡 준비', desc: '자유곡 선정 및 반복 연습', song: '(자유곡)' },
            { week: 12, title: '작은 음악회', desc: '발표 및 수료', song: '전체 곡' },
        ]
    },
    guitar: {
        name: '기타', emoji: '🎸', color: '#8b5cf6', color2: '#a78bfa', max: 40,
        weeks: [
            { week: 1, title: '기타와 첫 만남', desc: '기타 구조, 바른 자세, 줄 이름 알기', song: '(개방현 소리)' },
            { week: 2, title: '튜닝과 개방현', desc: '튜너 사용법, 개방현 소리 듣기', song: '(튜닝 연습)' },
            { week: 3, title: '첫 코드 Em', desc: '가장 쉬운 코드, 스트럼 기초', song: '(Em 연습)' },
            { week: 4, title: '친구 코드 Am', desc: 'Am 코드 잡기, Em-Am 전환', song: '사랑의 인사' },
            { week: 5, title: '다운 스트로크', desc: '4비트 다운 스트럼 연습', song: '(리듬 연습)' },
            { week: 6, title: 'C코드 배우기', desc: 'C코드 운지, Am-C 전환', song: '학교 종' },
            { week: 7, title: 'G코드 배우기', desc: 'G코드 운지, C-G 전환', song: '나비야' },
            { week: 8, title: '4코드 송', desc: 'Em-Am-C-G 진행으로 곡 연주', song: '봄봄봄' },
            { week: 9, title: '8비트 스트럼', desc: '다운-업 스트로크 연습', song: '거미' },
            { week: 10, title: 'D코드 배우기', desc: 'D코드 운지, 코드 전환 연습', song: '동물농장' },
            { week: 11, title: '칼립소 리듬', desc: '가장 많이 쓰는 리듬 패턴', song: '올챙이와 개구리' },
            { week: 12, title: '첫 번째 노래', desc: '간단한 동요 반주하기', song: '곰 세 마리' },
            { week: 13, title: '뮤트 스트럼', desc: '음 끊기 기법', song: '(리듬 연습)' },
            { week: 14, title: '마이너 코드들', desc: 'Dm, Em, Am 복습 및 활용', song: '작은 별' },
            { week: 15, title: '셔플 리듬', desc: '스윙 느낌 리듬 연주', song: '캠프파이어' },
            { week: 16, title: 'TAB 악보 읽기', desc: '멜로디 기초 연주', song: '(멜로디 연습)' },
            { week: 17, title: '아르페지오 기초', desc: '손가락 피킹 패턴', song: '로망스(일부)' },
            { week: 18, title: 'MR 반주 합주', desc: '반주 음원에 맞춰 연주', song: '(합주)' },
            { week: 19, title: '기초 발표회', desc: '발표회 곡 연주', song: '(선택곡)' },
            { week: 20, title: '기초 종합 복습', desc: '기초 과정 점검 및 수료', song: '-' },
            { week: 21, title: '바레 코드 F', desc: '가장 어려운 관문, F코드', song: '(F코드 연습)' },
            { week: 22, title: '바레 코드 Bm', desc: 'Bm코드 잡기', song: '(Bm 연습)' },
            { week: 23, title: '전조 연습', desc: '카포 사용법', song: '(카포 활용곡)' },
            { week: 24, title: '16비트 스트럼', desc: '빠른 리듬 패턴', song: '(리듬 연습)' },
            { week: 25, title: '컷팅 주법', desc: '리듬에 악센트 넣기', song: '(컷팅 연습)' },
            { week: 26, title: '해머온/풀오프', desc: '왼손 기법', song: '(기법 연습)' },
            { week: 27, title: '슬라이드', desc: '음 이동 기법', song: '(기법 연습)' },
            { week: 28, title: '핑거스타일 기초', desc: '엄지+손가락 패턴', song: '(핑거스타일)' },
            { week: 29, title: '핑거스타일 곡 1', desc: '쉬운 핑거스타일 곡', song: '(편곡)' },
            { week: 30, title: '핑거스타일 곡 2', desc: '중급 핑거스타일', song: '(편곡)' },
            { week: 31, title: '블루스 기초', desc: '12마디 블루스', song: '블루스 잼' },
            { week: 32, title: '팝송 반주 1', desc: '인기곡 코드 분석', song: '(인기곡)' },
            { week: 33, title: '팝송 반주 2', desc: '노래하며 반주', song: '(인기곡)' },
            { week: 34, title: '솔로 기초', desc: '펜타토닉 스케일', song: '(스케일 연습)' },
            { week: 35, title: '솔로 연주', desc: '간단한 솔로 만들기', song: '(솔로 연습)' },
            { week: 36, title: '앙상블', desc: '합주 연습', song: '(합주곡)' },
            { week: 37, title: '편곡 도전', desc: '좋아하는 곡 편곡', song: '(편곡)' },
            { week: 38, title: '졸업곡 준비 1', desc: '발표곡 선정', song: '(자유곡)' },
            { week: 39, title: '졸업곡 준비 2', desc: '완성도 높이기', song: '(자유곡)' },
            { week: 40, title: '졸업 음악회', desc: '수료 발표', song: '전체 레퍼토리' },
        ]
    },
    recorder: {
        name: '리코더', emoji: '🎶', color: '#ec4899', color2: '#f472b6', max: 20,
        weeks: [
            { week: 1, title: '리코더와 친해지기', desc: '악기 소개, 바른 자세, 왼손 잡기', song: '(소리 탐색)' },
            { week: 2, title: '시(B)음 불기', desc: '시(B)음 운지, 텅잉 기초', song: '(시음 연습)' },
            { week: 3, title: '라(A)음 익히기', desc: '라(A) 운지, 시-라 연결', song: '(시-라 연습)' },
            { week: 4, title: '솔(G)음 익히기', desc: '솔(G) 운지, 솔-라-시 연습', song: '비행기(앞부분)' },
            { week: 5, title: '첫 곡 도전', desc: '시-라-솔만으로 연주', song: '비행기' },
            { week: 6, title: '파(F) 운지', desc: '양손 사용 시작, 호흡 연습', song: '학교 종(앞부분)' },
            { week: 7, title: '미(E) 운지', desc: '미(E) 추가', song: '학교 종' },
            { week: 8, title: '레(D) 운지', desc: '레(D) 추가', song: '나비야' },
            { week: 9, title: '도(C) 운지', desc: '8음계 완성!', song: '작은 별' },
            { week: 10, title: '높은 도(C\')', desc: '고음역 시작, 호흡 조절', song: '거미' },
            { week: 11, title: '높은 레(D\')', desc: '고음 안정적 소리내기', song: '곰 세 마리' },
            { week: 12, title: '스타카토', desc: '짧은 음 표현', song: '산토끼' },
            { week: 13, title: '레가토', desc: '부드러운 음 연결', song: '고향의 봄' },
            { week: 14, title: '점음표와 쉼표', desc: '리듬감 살리기', song: '아빠 힘내세요' },
            { week: 15, title: '셈여림', desc: '세게/여리게 연주', song: '뻐꾸기' },
            { week: 16, title: '2중주', desc: '두 파트 나누어 합주', song: '(2중주곡)' },
            { week: 17, title: '자유곡 연습 1', desc: '발표곡 선정', song: '(자유곡)' },
            { week: 18, title: '자유곡 연습 2', desc: '반복 연습', song: '(자유곡)' },
            { week: 19, title: '리허설', desc: '발표 예행 연습', song: '전체 곡' },
            { week: 20, title: '작은 음악회', desc: '발표 및 수료', song: '-' },
        ]
    },
    piano: {
        name: '피아노', emoji: '🎹', color: '#3b82f6', color2: '#60a5fa', max: 40,
        weeks: [
            { week: 1, title: '피아노와 첫 만남', desc: '건반 이름, 바른 자세, 손 모양', song: '(건반 탐색)' },
            { week: 2, title: '오른손 도레미', desc: '1-2-3 손가락 (도-레-미)', song: '(음계 연습)' },
            { week: 3, title: '오른손 파솔', desc: '4-5 손가락 추가(파-솔)', song: '(음계 연습)' },
            { week: 4, title: '왼손 도레미파솔', desc: '왼손 5-4-3-2-1 연습', song: '비행기(왼손)' },
            { week: 5, title: '양손 연습', desc: '양손 번갈아 치기', song: '학교 종' },
            { week: 6, title: '첫 곡', desc: '비행기 (오른손 완곡)', song: '비행기' },
            { week: 7, title: '쉬운 동요', desc: '학교 종, 나비야 연주', song: '나비야' },
            { week: 8, title: '4분/2분음표', desc: '리듬 패턴 연습', song: '작은 별' },
            { week: 9, title: '온음표/쉼표', desc: '긴 음과 쉼표 지키기', song: '거미' },
            { week: 10, title: '양손 동시 연주', desc: '간단한 양손 곡', song: '곰 세 마리' },
            { week: 11, title: '코드 기초', desc: '도미솔(C) 화음', song: '(화음 연습)' },
            { week: 12, title: '화음 반주', desc: '왼손 화음+오른손 멜로디', song: '산토끼' },
            { week: 13, title: '레가토', desc: '이어서 치기', song: '고향의 봄' },
            { week: 14, title: '스타카토', desc: '끊어서 치기', song: '뻐꾸기' },
            { week: 15, title: '셈여림', desc: '세게/여리게 표현', song: '아기 코끼리' },
            { week: 16, title: '페달 사용', desc: '서스테인 페달 기초', song: '(페달 연습)' },
            { week: 17, title: '8분음표', desc: '빠른 리듬 연주', song: '징글벨' },
            { week: 18, title: '왼손 아르페지오', desc: '화음 풀어서 치기', song: '(아르페지오)' },
            { week: 19, title: '기초 발표', desc: '배운 곡 발표', song: '(선택곡)' },
            { week: 20, title: '기초 종합 복습', desc: '기초 과정 정리 및 수료', song: '-' },
            { week: 21, title: '가단조(Am)', desc: '단조 음계 이해', song: '슬픈 인형' },
            { week: 22, title: '사장조(G)', desc: '조표 이해, #(샵)', song: '(사장조 연습)' },
            { week: 23, title: '바장조(F)', desc: '♭(플랫) 이해', song: '(바장조 연습)' },
            { week: 24, title: '16분음표', desc: '더 빠른 리듬', song: '(리듬 연습)' },
            { week: 25, title: '점음표', desc: '점4분음표 리듬', song: '(점음표 연습)' },
            { week: 26, title: '당김음', desc: '싱코페이션 리듬 변형', song: '(리듬 연습)' },
            { week: 27, title: '왼손 패턴 확장', desc: '다양한 반주 패턴', song: '(반주 연습)' },
            { week: 28, title: '양손 독립', desc: '다른 리듬 양손 연주', song: '(양손 연습)' },
            { week: 29, title: '클래식 소품 1', desc: '미뉴에트 등 클래식', song: '미뉴에트' },
            { week: 30, title: '클래식 소품 2', desc: '소나티나 일부분', song: '소나티나' },
            { week: 31, title: '팝송 반주', desc: '코드 반주 기법', song: '(인기곡)' },
            { week: 32, title: '팝송 연주', desc: '인기곡 편곡 연주', song: '(인기곡)' },
            { week: 33, title: '연탄곡 기초', desc: '4hands 연주', song: '(연탄곡)' },
            { week: 34, title: '페달 심화', desc: '하프 페달, 소프트 페달', song: '(페달 연습)' },
            { week: 35, title: '즉흥 연주', desc: '간단한 멜로디 만들기', song: '(자유 멜로디)' },
            { week: 36, title: '편곡 도전', desc: '좋아하는 곡 편곡', song: '(편곡)' },
            { week: 37, title: '앙상블', desc: '다른 악기와 합주', song: '(합주곡)' },
            { week: 38, title: '졸업곡 준비 1', desc: '발표곡 선정', song: '(자유곡)' },
            { week: 39, title: '졸업곡 준비 2', desc: '완성도 높이기', song: '(자유곡)' },
            { week: 40, title: '졸업 음악회', desc: '수료 발표', song: '전체 레퍼토리' },
        ]
    },
    drums: {
        name: '드럼/카혼', emoji: '🥁', color: '#f97316', color2: '#fb923c', max: 20,
        weeks: [
            { week: 1, title: '리듬의 세계', desc: '카혼/드럼 소개, 바른 자세, 기본 타법', song: '(타법 연습)' },
            { week: 2, title: '베이스와 톤', desc: '베이스/톤 구분, 킥/스네어', song: '(기본 타격)' },
            { week: 3, title: '4비트 기초', desc: '기본 4비트 리듬', song: '(4비트 연습)' },
            { week: 4, title: '8비트 리듬 1', desc: '하이햇 추가, 기본 8비트', song: '(8비트 연습)' },
            { week: 5, title: '8비트 리듬 2', desc: '8비트 변형 패턴', song: '곰 세 마리' },
            { week: 6, title: '필인 기초', desc: '간단한 필인(마디 전환)', song: '(필인 연습)' },
            { week: 7, title: '악센트', desc: '세게/여리게, 리듬에 강약', song: '나비야' },
            { week: 8, title: '16비트 기초', desc: '16비트 하이햇 패턴', song: '(16비트 연습)' },
            { week: 9, title: '셔플 리듬', desc: '스윙 느낌 연주', song: '(셔플 연습)' },
            { week: 10, title: '동요 반주', desc: '동요에 맞춰 반주', song: '학교 종' },
            { week: 11, title: '팝 리듬', desc: '대중가요 기본 리듬', song: '(팝곡)' },
            { week: 12, title: '로큰롤 리듬', desc: '신나는 로큰롤 비트', song: '(로큰롤)' },
            { week: 13, title: '댄스 비트', desc: '4 on the floor 리듬', song: '(댄스곡)' },
            { week: 14, title: '레게 리듬', desc: '오프비트 강조', song: '(레게곡)' },
            { week: 15, title: '라틴 리듬', desc: '룸바, 차차차 기초', song: '(라틴곡)' },
            { week: 16, title: '합주 연습 1', desc: '다른 악기와 호흡', song: '(합주곡)' },
            { week: 17, title: '합주 연습 2', desc: '곡 전체 구조 연주', song: '(합주곡)' },
            { week: 18, title: '자유곡 연습', desc: '발표곡 선정 및 연습', song: '(자유곡)' },
            { week: 19, title: '리허설', desc: '최종 리허설', song: '전체 곡' },
            { week: 20, title: '작은 음악회', desc: '발표 및 수료', song: '-' },
        ]
    },
};

const CUSTOM_EMOJIS = ['🎵', '🎶', '🎷', '🎺', '🎻', '🪕', '🥁', '🪘', '🎤', '🎧', '🪈', '🪗', '🪇', '🎹', '🎸', '🎼'];
const COLOR_PALETTE = [
    { color: '#ff7b6b', color2: '#ff9e5e' }, { color: '#4ecdc4', color2: '#45b7d1' },
    { color: '#f59e0b', color2: '#fbbf24' }, { color: '#8b5cf6', color2: '#a78bfa' },
    { color: '#ec4899', color2: '#f472b6' }, { color: '#3b82f6', color2: '#60a5fa' },
    { color: '#f97316', color2: '#fb923c' }, { color: '#22c55e', color2: '#4ade80' },
    { color: '#e11d48', color2: '#fb7185' }, { color: '#06b6d4', color2: '#22d3ee' },
];
